version: "3"
services:
  prometheus:
    build: prometheus
    image: prometheus
    ports:
      - "9090:9090"
    restart: on-failure
    networks:
      - weather_network
  application:
    build: Back-End
    image: application
    depends_on:
      - prometheus
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - weather_network
  front:
    build: Front-End
    image: frontend
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - weather_network

networks:
  weather_network:
