version: "3.3"
services:
  prometheus:
    build: prometheus
    image: prometheus
    networks:
      back:
        ipv4_address: 172.18.0.10
    ports:
      - "9090:9090"
    restart: on-failure
  application:
    build: .
    image: application
    depends_on:
      - prometheus
    networks:
      back:
        ipv4_address: 172.18.0.11
    ports:
      - "8080:8080"
    restart: on-failure

networks:
  back:
    ipam:
      config:
        - subnet: 172.18.0.0/24
