global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'weather'
    metrics_path: '/metrics'
    basic_auth:
      username: prometheus
      password: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
